FROM python:3.9-slim
RUN apt-get update && apt-get install -y build-essential cmake libopenblas-dev liblapack-dev && pip install dlib
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:$PORT", "app:app"]
